[module]
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.imports]]
path = "github.com/bep/alpine/v3"
[[module.imports.mounts]]
source = "packages"
target = "assets/jslibs/alpinejs/v3"
