[module]
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.imports]]
path = "github.com/ryangjchandler/spruce"
[[module.imports.mounts]]
source = "dist"
target = "assets/jslibs/spruce"

